apiVersion: v1
kind: LimitRange
metadata:
  name: beamray-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: "1"
        memory: 1Gi
