apiVersion: v1
kind: ResourceQuota
metadata:
  name: beamray-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "6"
    limits.memory: 12Gi
    requests.storage: 20Gi
    persistentvolumeclaims: "6"
    pods: "30"
    services: "20"
    configmaps: "50"
    secrets: "50"
    count/ingresses.networking.k8s.io: "10"
