apiVersion: v1
kind: ServiceAccount
metadata:
  name: beamray-dev-deployer
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: beamray-dev-runtime
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
automountServiceAccountToken: false
