apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-system
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://cloudnative-pg.github.io/charts'
    targetRevision: 0.28.0
    chart: cloudnative-pg
    helm:
      values: |
        # We don't strictly need any overrides for a basic setup, 
        # but leaving this block here makes it easy to add them later.
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true 