apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: envoy-gateway-system
    server: https://kubernetes.default.svc
  source:
    chart: gateway-helm
    repoURL: registry-1.docker.io/envoyproxy
    targetRevision: v1.7.1
  project: default
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true