apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: beamray-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sbrerup/dripcloud.git
    targetRevision: HEAD
    path: manifests/beamray-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: beamray-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
