apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dripcraft
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/sbrerup/dripcloud.git'
      targetRevision: HEAD
      path: manifests/minecraft
    - repoURL: 'https://itzg.github.io/minecraft-server-charts'
      targetRevision: 5.1.2
      chart: minecraft
      helm:
        values: |
          minecraftServer:
            eula: "true"
            type: "PAPER"
            version: "1.21.11"
            whitelist:
            ops:
            forcegameMode: true
            levelSeed:
            gameMode: survival
            motd: "Welcome to DripCraft Multiverse"
            pvp: false
  
            serviceType: LoadBalancer            
  
            viewDistance: 10
            memory: 8g
  
            modUrls: []
            pluginUrls:
              - "https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot"
              - "https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot"
              - "https://github.com/EssentialsX/Essentials/releases/download/2.21.2/EssentialsX-2.21.2.jar"
              - "https://cdn.modrinth.com/data/3wmN97b8/versions/9qZJ8PBg/multiverse-core-5.6.1.jar"
              - "https://cdn.modrinth.com/data/qvdtDX3s/versions/lvgetpFU/multiverse-inventories-5.3.2.jar"
              - "https://cdn.modrinth.com/data/1u6JkXh5/versions/p8T2aZ8U/worldedit-bukkit-7.4.2.jar"
              - "https://github.com/BentoBoxWorld/BentoBox/releases/download/3.14.2/BentoBox-3.14.2.jar"
  
            rcon:
              enabled: true
              serviceType: LoadBalancer
              existingSecret: "dripcraft-rcon-secret"
              secretKey: "rcon-password"
  
            extraPorts:
              - name: geyser
                containerPort: 19132
                protocol: UDP
                service:
                  enabled: true
                  type: LoadBalancer
                  port: 19132
                  annotations:
                    io.cilium/lb-ipam-ips: "10.1.2.250"
                    io.cilium/lb-ipam-sharing-key: "dripcraft-shared"
              - name: bluemap
                containerPort: 8100
                protocol: TCP
                service:
                  enabled: true
                  type: ClusterIP
                  port: 8100

          serviceAnnotations:
            io.cilium/lb-ipam-ips: "10.1.2.250"
            io.cilium/lb-ipam-sharing-key: "dripcraft-shared"

          rconServiceAnnotations:
            io.cilium/lb-ipam-ips: "10.1.2.250"
            io.cilium/lb-ipam-sharing-key: "dripcraft-shared"

          extraEnv:
            ENABLE_ROLLING_LOGS: "true"
            OVERRIDE_SERVER_PROPERTIES: "true"
            FORCE_WORLD_COPY: "false"
  
          persistence:
            annotations: {}
            dataDir:
              enabled: true
              size: 100Gi
  
          resources:
            requests:
              memory: 8Gi
              cpu: 1
            limits:
              memory: 12Gi
              cpu: 6

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dripcraft
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true 