apiVersion: gateway.networking.k8s.io/v1alpha2 # TCPRoute is often still in v1alpha2
kind: TCPRoute
metadata:
  name: java-route
  namespace: default
spec:
  parentRefs:
  - name: dripcloud-gateway
    sectionName: java-tcp
  rules:
  - backendRefs:
    - name: mc-minecraft-server # The main Java service
      port: 25565