apiVersion: gateway.networking.k8s.io/v1alpha2 # TCPRoute is often still in v1alpha2
kind: TCPRoute
metadata:
  name: dripcraft-default-route
spec:
  parentRefs:
  - name: dripcraft-gateway
    sectionName: dripcraft-default
  rules:
  - backendRefs:
    - name: dripcraft-minecraft
      port: 25565
