name: Dripcraft Portal Image

on:
  push:
    branches:
      - main
    paths:
      - services/dripcraft-portal/**
      - .github/workflows/dripcraft-portal-image.yaml
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Test
        working-directory: services/dripcraft-portal
        run: python -m unittest discover -s tests

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: services/dripcraft-portal
          push: true
          tags: |
            ghcr.io/sbrerup/dripcraft-portal:latest
            ghcr.io/sbrerup/dripcraft-portal:${{ github.sha }}
